name: Release

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**.md'
  release:
    types:
      - published

jobs:
  build:
    name: Build and Release ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # MacOS
          - os: darwin
            arch: amd64
            bit: "64"
            ext: zip
          - os: darwin
            arch: arm64
            bit: "64"
            ext: zip
          # Linux
          - os: linux
            arch: 386
            bit: "32"
            ext: tar.gz
          - os: linux
            arch: amd64
            bit: "64"
            ext: tar.gz
          - os: linux
            arch: arm64
            bit: "64"
            ext: tar.gz
          - os: linux
            arch: arm
            goarm: 5
            bit: "32"
            ext: tar.gz
          - os: linux
            arch: arm
            goarm: 6
            bit: "32"
            ext: tar.gz
          - os: linux
            arch: arm
            goarm: 7
            bit: "32"
            ext: tar.gz
          - os: linux
            arch: mips
            bit: "32"
            ext: tar.gz
          - os: linux
            arch: mips64
            bit: "64"
            ext: tar.gz
          - os: linux
            arch: mipsle
            bit: "32"
            ext: tar.gz
          - os: linux
            arch: mips64le
            bit: "64"
            ext: tar.gz
          # Windows
          - os: windows
            arch: 386
            bit: "32"
            ext: zip
          - os: windows
            arch: amd64
            bit: "64"
            ext: zip
          - os: windows
            arch: arm64
            bit: "64"
            ext: zip

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.X'

      - name: Get the version
        run: echo "VERSION=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV

      - name: Build
        run: |
          echo "Building for OS: ${{ matrix.os }}, Arch: ${{ matrix.arch }}, Version: ${{ env.VERSION }}"
          output_name="CloudflareST_${{ matrix.os }}_${{ matrix.arch }}${{ matrix.goarm }}"
          echo "Output name: $output_name"

          command="GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} GOARM=${{ matrix.goarm }} go build -ldflags \"-s -w -X main.version=${{ env.VERSION }}\" -v -o $output_name"
          echo "Running command: $command"
          eval $command

          if [ "${{ matrix.ext }}" = "zip" ]; then
            zip $output_name.${{ matrix.ext }} $output_name
          else
            tar cvzf $output_name.${{ matrix.ext }} $output_name
          fi
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: CloudflareST_*.${{ matrix.ext }}

      - name: Upload packages
        uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'release'
        with:
          repo_token: ${{ github.token }}
          file: "CloudflareST_*"
          tag: ${{ github.ref }}
          file_glob: true
